---
- name: Check for masquerading
  shell: firewall-cmd --zone {{ firewalld_masq_zone }} --query-masquerade
  register: masquerade
  check_mode: no
  changed_when: False
  failed_when: masquerade.rc >= 2

- name: Add masquerading to zone
  shell: firewall-cmd --zone {{ firewalld_masq_zone }} --add-masquerade --permanent
  when: masquerade.rc == 1
