---
- name: set ip_forward to 1 to allow kickstarting of network nodes
  sysctl: name=net.ipv4.ip_forward value=1 sysctl_set=yes reload=no

- name: get firewalld state
  shell: firewall-cmd --state
  ignore_errors: true
  check_mode: no
  register: firewalld_state
  changed_when: False

- import_tasks: iptables.yml
  when: firewalld_state.rc != 0

- import_tasks: firewalld.yml
  when: firewalld_state.rc == 0
